### ISSUE TITLE
Consider merge with Manishearth/rust-clippy

### ISSUE THREAD

**Issue by ctjhoa** [llogiq/extra_lints#1]
Hi,

I think this module has the same goal as your's. 
https://github.com/Manishearth/rust-clippy

Please consider merge between both to avoid duplication.

**Comment by llogiq** [comment]
I'm not sure if I can MPL my code retroactively, as the MPL is expressly incompatible to other licenses as per definition 1.5. Pity, but I cannot afford a lawyer to check.

I'll contact Manish and we'll see what we can do.

**Comment by Susurrus** [comment]
Its your code so you can relicense it however you see fit, including dropping a license.

**Comment by llogiq** [comment]
I have looked at the legalese and to the best of my knowledge there is nothing preventing me from merging my code into rust-clippy. I have also contacted Manish and he's already given me contributor rights.

So short story short, this project _will_ be merged into rust-clippy. I'll leave this issue open until I'm done merging.

**Comment by llogiq** [comment]
I've submitted a pull request to Manish (because just pushing stuff seemed somehow impolite). Once he pulls, I'm going to put a big notice into the README to lead people to clippy.

From my point of view, this issue is closed.
